import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/context/AuthProvider";
import Navbar from "@/components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Providers } from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Earn Money by Driving or Get a Ride Now | Uber India",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>
    //     <NextIntlClientProvider messages={messages}>
    //       <AuthProvider>
    //         <Providers>
    //           <ToastContainer />
    //            <Navbar />
                <>{children}</>
    //         </Providers>
    //       </AuthProvider>
    //     </NextIntlClientProvider>
    //   </body>
    // </html>
  );
}
